# Generated by Django 5.0.1 on 2024-02-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_alter_student_thesis_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='thesis',
            name='average',
            field=models.FloatField(default=0),
        ),
    ]
