# Generated by Django 5.0.1 on 2024-02-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_alter_student_unique_together_thesis_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='average',
        ),
    ]
